language: python
python:
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION='>=1.10,<1.11'
  - DJANGO_VERSION='>=1.11,<1.12'
  - DJANGO_VERSION='>=2.2,<2.3'
install:
  - "pip install -q Django$DJANGO_VERSION"
  - pip install -q -r requirements.txt
script: python manage.py test
sudo: false
